### ISSUE TITLE
missing classes

### ISSUE THREAD

**Issue by csabagidofalvi** [KalebKE/FSensor#20]
Hi.
I'm trying to use your OrientationKalmanFusion example,
but can't find the class "OrientationFusion" in the project.

private OrientationFusion orientationFusion;
then initialised as orientationFusion = new OrientationKalmanFusion();

i tried declaring it as "OrientationFused" and initialize it with KalmanFusion but the methods:
-setAcceleration
-setMagneticField
-filter
are missing still missing.
Plese help me with some clarification how are this implemented.

**Comment by KalebKE** [comment]
Hello,

I have been making some changes to the interface and haven't had a chance to update the documentation,  but I have a working example in [GyroscopeExplorer](https://github.com/KalebKE/GyroscopeExplorer/blob/master/app/src/main/java/com/kircherelectronics/gyroscopeexplorer/activity/GyroscopeActivity.java) that is backed by v1.2.

**Comment by csabagidofalvi** [comment]
Thx for the quick respons.
I used the suggested example, it works!
