### ISSUE TITLE
LinearAccelerationFusion: low-pass filter?

### ISSUE THREAD

**Issue by fabio1843** [KalebKE/FSensor#22]
Hi,
I try to use LinearAccelerationFusion to find linearAcceleration and after that try to remap acceleration in world coordinate.

```
if (event.sensor.getType() == Sensor.TYPE_ACCELEROMETER)
{
               System.arraycopy(event.values, 0, acceleration, 0, event.values.length);
                hasAcceleration = true;
                linearAcceleration = linearAccelerationFusion.filter(acceleration);
}


float[] deviceRelativeAcceleration = new float[4];
                        deviceRelativeAcceleration[0] = linearAcceleration[0];
                        deviceRelativeAcceleration[1] = linearAcceleration[1];
                        deviceRelativeAcceleration[2] = linearAcceleration[2];
                        deviceRelativeAcceleration[3] = 0;


                        float[] R = new float[16], I = new float[16], earthAcc = new float[16];

                        SensorManager.getRotationMatrix(R, I, linearAccelerationFusion.getGravity(), magnetic);

                        float[] inv = new float[16];

                        android.opengl.Matrix.invertM(inv, 0, R, 0);
                        android.opengl.Matrix.multiplyMV(earthAcc, 0, inv, 0, deviceRelativeAcceleration, 0);

                        float [] earthAccNorm = new float[3];
                        earthAccNorm[0] = earthAcc[0]/G_CONSTANT;
                        earthAccNorm[1] = earthAcc[1]/G_CONSTANT;
                        earthAccNorm[2] = earthAcc[2]/G_CONSTANT;
```

But the earthNorm takes strange values.

**Comment by KalebKE** [comment]
Hi,

At a glance everything looks correct. 

I would check the return value of SensorManager.getRotationMatrix() to make sure it is returning true.

The next place I would look is making sure your magnetic field measurements don't have significant hard or soft iron distortions. You can use AzimuthUtil.getAzimuth() to double check the values look reasonable.

**Comment by Piyawat01057** [comment]
> สวัสดี
> ฉันพยายามใช้ LinearAccelerationFusion เพื่อค้นหา linearAcceleration และหลังจากนั้นพยายามทำการแมปการเร่งความเร็วในพิกัดโลก
> 
> ```
> if (event.sensor.getType() == Sensor.TYPE_ACCELEROMETER)
> {
>                System.arraycopy(event.values, 0, acceleration, 0, event.values.length);
>                 hasAcceleration = true;
>                 linearAcceleration = linearAccelerationFusion.filter(acceleration);
> }
> 
> 
> float[] deviceRelativeAcceleration = new float[4];
>                         deviceRelativeAcceleration[0] = linearAcceleration[0];
>                         deviceRelativeAcceleration[1] = linearAcceleration[1];
>                         deviceRelativeAcceleration[2] = linearAcceleration[2];
>                         deviceRelativeAcceleration[3] = 0;
> 
> 
>                         float[] R = new float[16], I = new float[16], earthAcc = new float[16];
> 
>                         SensorManager.getRotationMatrix(R, I, linearAccelerationFusion.getGravity(), magnetic);
> 
>                         float[] inv = new float[16];
> 
>                         android.opengl.Matrix.invertM(inv, 0, R, 0);
>                         android.opengl.Matrix.multiplyMV(earthAcc, 0, inv, 0, deviceRelativeAcceleration, 0);
> 
>                         float [] earthAccNorm = new float[3];
>                         earthAccNorm[0] = earthAcc[0]/G_CONSTANT;
>                         earthAccNorm[1] = earthAcc[1]/G_CONSTANT;
>                         earthAccNorm[2] = earthAcc[2]/G_CONSTANT;
> ```
> 
> แต่ earthNorm ใช้ค่าแปลก ๆ
