### ISSUE TITLE
From OrientationFusion to OrientationFused

### ISSUE THREAD

**Issue by krenargashi** [KalebKE/FSensor#23]
Hi, i really love your software! But i don't understand, how OrientationFused should be used now, since it was changed 2 months ago and the documentation still contains OrientationFusion.

**Comment by KalebKE** [comment]
Hi, 

Apologies for the terrible state of the documentation, I just haven't had the time to update it. However, the https://github.com/KalebKE/GyroscopeExplorer project has been updated and provides examples on how to use the updated API.
