### ISSUE TITLE
values from ComplementaryLinearAccelerationSensor too large at rest

### ISSUE THREAD

**Issue by pvvvgithub** [KalebKE/FSensor#35]
I am using the latest version 2.1. At rest (phone is on table), the ComplementaryLinearAccelerationSensor always returns too large values. 
For example :
x: 0.2, y: 13 z: 9 
Code is very simple : https://github.com/pvvvgithub/test_ComplementaryLinearAccelerationSensor/tree/master/app/src/main/java/com/example/android/demo
![image](https://user-images.githubusercontent.com/67832681/86719939-bed78980-c04e-11ea-833f-a823efde6057.png)

**Comment by KalebKE** [comment]
Hi,
Are you certain your phone has a magnetic and gyroscope sensor?

**Comment by pvvvgithub** [comment]
> Hi,
> Are you certain your phone has a magnetic and gyroscope sensor?
Hi! Yes. My phone (samsung galaxy note 10+) have a magnetic and gyroscope sensor .

**Comment by KalebKE** [comment]
Presumably the device is static and you are expecting values close to zero? Could you quickly hook your project into SensorManager and verify that it is giving you sane values for the acceleration?

**Comment by pvvvgithub** [comment]
I checked the values through https://play.google.com/store/apps/details?id=com.kircherelectronics.accelerationexplorer:
-Android Linear Acceleration
- LPF Linear Acceleration
Complimentary Fusion.
 Values are close to zero.

**Comment by pvvvgithub** [comment]
@KalebKE  what other information should I send you?

**Comment by KalebKE** [comment]
@pvvvgithub I'll try to take a look at the code tomorrow. I changed the order of the axis in v2.1 and may have forgotten to reorder that filter.

**Comment by pvvvgithub** [comment]
Hi! Could you figure it out?

**Comment by KalebKE** [comment]
@pvvvgithub 

I believe I found and fixed the issue in https://github.com/KalebKE/FSensor/pull/36. I have released v2.2 with the fix.

**Comment by pvvvgithub** [comment]
@KalebKE  Thanks, it got better. But the values are still great. 
First values: 0.11 .  After 1 second, the values are already 0.2 and continues to increase . See log.txt. The phone is on the table all this time without movement. 
[log.txt](https://github.com/KalebKE/FSensor/files/4941118/log.txt)
