### ISSUE TITLE
Syntax error on maven block

### ISSUE THREAD

**Issue by sauloaguiar** [KalebKE/FSensor#4]
Hi, 

I noticed that you created a code snippet to help on how to add the maven repository that hosts the library. It contains
```
maven {
  maven { url "https://jitpack.io" }
}
```
and it should be pasted inside the project level `build.gradle` file as you explained.

I guess that the maven block is duplicated and that the correct code snippet should be 
```
maven {
  url "https://jitpack.io"
}
```

If this proceeds, let me know if I can help more by sending a PR.
Thanks for the nice effort of putting up this code library and all the explanation regarding the filtering. Really nice work!

**Comment by KalebKE** [comment]
Thanks for pointing this out! Fixed.
